name: Pages Deployment

on:
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build DumpFormatter
        run: |
          dotnet publish -c Release -o ./_bin ./src/DumpFormatter/DumpFormatter.csproj

      - name: Build Pages
        run: |
          ./src/Pages/tools/deploy_build.ps1 -RootDir . -DumpFormatterExePath ./_bin/DumpFormatter.exe -OutputDir ./_pages

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: ./_pages

  deploy:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: windows-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
